### ISSUE TITLE
Mode=link produces no link

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#129]
Why does this API request does not produce a link?

http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&informat=text&mode=link&input=Wild+Atlantic+Way&outformat=turtle

The Wild Atlantic Way has a label: http://dbpedia.org/page/Wild_Atlantic_Way

**Comment by m1ci** [comment]
Due to unknown reason the resource "http://dbpedia.org/resource/Wild_Atlantic_Way" is not indexed in Solr.
Just queried for `resource: "http://dbpedia.org/resource/Wild_Atlantic_Way"` via the Solr interface and there is no such record.
Reasons: maybe the entity was not present in the dump we used to index, or the entity was not indexed due to some issue.

**Comment by koidl** [comment]
Thanks @m1ci how do we solve it? Maybe update the dbpedia dump used?

In relation to this @jnehring how will we update the dbpedia file on our local installments? I guess there is some procedure we will have to follow. Just wondering if its documented.

**Comment by m1ci** [comment]
> Maybe update the dbpedia dump used?

we can do that.

> In relation to this @jnehring how will we update the dbpedia file on our local installments? I guess there is some procedure we will have to follow. Just wondering if its documented.

Same procedure for uploading new dataset.

**Comment by jnehring** [comment]
This works now. I think the datasets were re-indexed and so the issue was fixed
