### ISSUE TITLE
Create dataset does not work on freme-dev

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#68]
Moved from #58 

This CURL
```
 curl -X POST --header "Content-Type: application/n-triples" --header "Accept: application/json" -d test.txt "http://api-dev.freme-project.eu/current/e-entity/freme-ner/datasets?informat=turtle&name=test-jan&description=delete%20me&language=en"
```

With [this test.txt](https://github.com/freme-project/freme-ner/files/115654/test.txt) produces

```
{
  "exception": "eu.freme.broker.exception.BadRequestException",
  "path": "/e-entity/freme-ner/datasets",
  "message": "504 Gateway Timeout",
  "error": "Bad Request",
  "status": 400,
  "timestamp": 1454503947463
}
```

**Comment by nilesh-c** [comment]
Here’s what’s happening:

https://github.com/freme-project/freme-ner/blob/master/src/main/scala/org/elinker/core/api/process/Datasets.scala#L116

val d = new DatasetSimple(dataset.name, dataset.description, numEntities)
datasetDAO.save(d)

Note that SOLR indexing works correctly, I have verified that. In the above code, after the new dataset metadata is saved into the database, MySQL creates a row like:

28 | 1454619332035 | NULL               | NULL               |              0 |

DatasetSimple has 3 values: name, description, totalEntities - none of which get inserted into MySQL, NULL/0 instead. This is weird because retrieving DatasetSimple objects from the database work perfectly well.

Similar errors from SO:
http://stackoverflow.com/questions/16870454/null-values-are-insering-in-data-base-using-struts2-and-hibernate
http://stackoverflow.com/questions/5808860/hibernate-inserts-null-values-to-table-when-used-with-spring

**Comment by nilesh-c** [comment]
Bottomline, GET/DELETE requests work. But doing a POST (or creating a dataset) will break things and GET etc. will not work because of the NULL values in the dataset_simple table.. Only way to fix is to go into the MySQL instance (`mysql -u root -p`), use the password from src/main/resources/applicationContext.xml and execute `delete from dataset_simple where name is NULL;`

**Comment by sandroacoelho** [comment]
HI @nilesh-c , @m1ci

I figure out that  description and name keeps null on DatasetSimple constructor. I did a small refactor and now it works. 

Best,

**Comment by m1ci** [comment]
I just re-deployed FREME NER, but the issue still exists. Am I missing smth here?

Thanks,
Milan

**Comment by m1ci** [comment]
this is fixed.
