### ISSUE TITLE
updateDataset does not work

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#81]
I used the new Java API. The method updateDataset does not work. When I send a PUT request to update a dataset then it creates a new entry in the MySQL database instead of updating an existing entry. It does not seem to send any data to the solr server.

This is a blocker right now.

The current version of the codes is in branch architecture-update in the freme-ner repo. You can start the API using the main class "eu.freme.common.starter.FREMEStarter". Configuration is done in src/main/resources/application.properties

**Comment by sandroacoelho** [comment]
Hi @jnehring , @m1ci 

For  " When I send a PUT request to update a dataset then it creates a new entry in the MySQL database instead of updating an existing entry",  I made a small fix that solves the problem. It is in  issue81 branch (Also I merged with architecture-update) .

@jnehring : In architecture-update, I am getting compilation error

*symbol:*   class NotFoundException

*location:* package eu.freme.common.exception

And

*incompatible types:* java.lang.Iterable < eu.freme.common.persistence.model.DatasetSimple > 

cannot be converted to java.util.List < eu.freme.common.persistence.model.DatasetSimple >

I've tried to locate in github, which FREME Common branch contains these changes without success. Could you , please, help me with it?

"It does not seem to send any data to the solr server." : 

NER is using Solr and 8984 (http://rv2622.1blu.de:8984/solr/), but when I try to connect using telnet or a browser, does not work.  I have a Solr local instance and it works.

![Solr](https://www.dropbox.com/s/kf9ykrc6ryqe01k/freme-solr-issue-81.png?dl=1)

**Comment by m1ci** [comment]
> I've tried to locate in github, which FREME Common branch contains these changes without success. Could you , please, help me with it?

@jnehring Can you please comment on this?

> NER is using Solr and 8984 (http://rv2622.1blu.de:8984/solr/), but when I try to connect using telnet or a browser, does not work. I have a Solr local instance and it runs without problem. @m1ci: we can check the server together

The Solr instances are secured. Please send me your public IP so I can enable access from that IP. Send me your IP in a personal message.

**Comment by jnehring** [comment]
> symbol: class NotFoundException
> location: package eu.freme.common.exception

Sorry I forgot to commit some codes. I pushed them to FREME common. (branch architecture-update-master). They are included in the maven artifact also so dont worry how to get the codes, maven should do this for you.

> incompatible types: java.lang.Iterable < eu.freme.common.persistence.model.DatasetSimple >
> cannot be converted to java.util.List < eu.freme.common.persistence.model.DatasetSimple >

I cannot reproduce this bug.

I did:

```
git clone https://github.com/freme-project/freme-ner.git
git checkout origin/architecture-update
mvn install DskipTests=true
```

mvn install said "BUILD SUCCESS", without compilation errors.

**Comment by jnehring** [comment]
It works. Thank you!

**Comment by sandroacoelho** [comment]
:+1:
