### ISSUE TITLE
FREME NER failed on freme-live

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#84]
FREME NER failed on freme-live. The server process died and it is no longer running. I tried to restart it using `mvn scala:runDmainClass=org.elinker.core.api.Server` but this did not work.

1) Can you please restart it
2) Do you have any logfiles that can point us to the source of the problem?

**Comment by m1ci** [comment]
1) done: http://api.freme-project.eu/current/e-entity/freme-ner/datasets/
You can use the `start.sh` script to start it using `sh start.sh`

2) everything is logged in `log.txt`
From the log it looks freme ner crashed due to syntax error in the communication with the sparql endpoint. @sandroacoelho can you check what went wrong? Check the log file `.../elinker/freme-ner-0.5/freme-ner-latest/log.txt_sandro_to_check` for more info on the problem.

PS: the latest freme ner release is in `.../elinker/freme-ner-0.5/freme-ner-latest`

**Comment by jnehring** [comment]
I was working on freme-worker when FREME NER crashed. I started FREME NER using the new architecture. The new installation is separated from the old installations so I do not expect a relationship between the two but it is possible that something caused e.g. an OutOfMemory exception and then freme-ner crashed.

**Comment by jnehring** [comment]
Thanks for the quick fix

**Comment by jnehring** [comment]
This crash was related to the old architecture. No need to examine this further because it will be replaced soon.
