### ISSUE TITLE
problem with anchor of

### ISSUE THREAD

**Issue by jnehring** [freme-project/freme-ner#96]
http://api.freme-project.eu/current/e-entity/freme-ner/documents?language=en&dataset=dbpedia&informat=text&outformat=turtle&input=%22Simply%20Brilliant%22%20Charlie%20Byrne%E2%80%99s%20Bookshop%2C%20Galway.

produces (among other annotations)

```
<http://freme-project.eu/#char=2,34>
        a                     nif:Phrase , nif:RFC5147String , nif:String , nif:Word ;
        nif:anchorOf          "Simply Brilliant \\ '' Charlie Byrne"^^xsd:string ;
        nif:beginIndex        "2"^^xsd:int ;
        nif:endIndex          "34"^^xsd:int ;
        nif:referenceContext  
                <http://freme-project.eu/#char=0,54> ;
        itsrdf:taClassRef     
                    <http://nerd.eurecom.fr/ontology#Person> ;
        itsrdf:taConfidence   "0.7414872578533792"^^xsd:double .

<http://freme-project.eu/#char=0,52>
        a               nif:RFC5147String , nif:Context , nif:String ;
        nif:beginIndex  "0"^^xsd:nonNegativeInteger ;
        nif:endIndex    "52"^^xsd:nonNegativeInteger ;
        nif:isString    "\"Simply Brilliant\" Charlie Byrne’s Bookshop, Galway." .
```

I wonder how `Simply Brilliant\"`  turns into `Simply Brilliant \\ ''`. The problems are first the space after brilliant and 2nd why the \ is converted to \\.

Propably related to #95, #94 .

**Comment by xFran** [comment]
> I wonder how Simply Brilliant\" turns into Simply Brilliant \\ ''. The problems are first the space after brilliant and 2nd why the \ is converted to \.

Because your framework at some point while filtering the data is trying to escape "\" by adding another "\" which I strongly believe that in a previous process of the data the framework was trying to escape the double quotes ' " ' by adding a backslash eg. \".   

I would suggest to take a look at those filters and remember that some chars acts like comments in queries therefore ignored. This issues can lead to wrong queries. We have to keep all this in mind because it's also dangerous with the risks to accidentally delete data without even noticed immediately.

**Comment by jnehring** [comment]
In last developers call we agreed that @m1ci or @sandroacoelho will take a look at this.

**Comment by sandroacoelho** [comment]
Hi all,

We are leverage in Solr results (for mentions) instead of use the original text. It can "create" new 
characters like [here](https://github.com/freme-project/freme-ner/blob/2f538019c60f3c05107b4bf8ba93f4f243f45a85/src/main/java/org/elinker/core/api/java/serialize/NIFConverter.java#L84) and [here](https://github.com/freme-project/freme-ner/blob/2f538019c60f3c05107b4bf8ba93f4f243f45a85/src/main/java/org/elinker/core/api/java/serialize/NIFConverter.java#L85), or sometimes put new spaces, single quotes etc.

I am changing this approach to use the original. Please give me one more business day to change and test it.

**Comment by jnehring** [comment]
any news here, @sandroacoelho  ?

**Comment by sandroacoelho** [comment]
Hi @jnehring: I am doing my final tests. I intend to commit tomorrow

**Comment by sandroacoelho** [comment]
Hi @jnehring, @m1ci . Sorry for the big delay. 
Fixed. When are you testing  #95 and #95,  could you please include #57 too?   Thanks.

**Comment by jnehring** [comment]
Thank you @sandroacoelho . I will test #95, #96 and #57.

**Comment by jnehring** [comment]
Problem fixed. Thank you
